### ISSUE TITLE
NONG songs crash the game

### ISSUE THREAD

**Issue by Sent1nelllll** [elnexreal/menuloop_randomizer#14] opened 2024-08-22 15:47 UTC
Everytime the mod tries to load a NONG song the mod crashes the game with the logs:

2024-08-22T18:46:08+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.4.0
Loader Commit: a533b5f
Bindings Commit: de6a02b
Installed mods: 33
Problems: 0

== Exception Information ==
C++ Exception: class std::out_of_range("stoi argument out of range")
Faulty Mod: Menu Loop Randomizer v1.4.0 (elnexreal.menuloop_randomizer)
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + cc95a (RaiseException + 138)
 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - C:\WINDOWS\SYSTEM32\MSVCP140.dll + 39652 (std::_Xout_of_range + 34)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\elnexreal.menuloop_randomizer\elnexreal.menuloop_randomizer.dll + daca
 - D:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\elnexreal.menuloop_randomizer\elnexreal.menuloop_randomizer.dll + 916d
 - D:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\elnexreal.menuloop_randomizer\elnexreal.menuloop_randomizer.dll + b6c7
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 000001BBD0F70872 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 3c0a5 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 000001BBD0F70872 (Hook handler)
 - 000001BBD13E1872 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 75d81
 - D:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 51b2c
 - 000001BBD13E1872 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 000001BBD0F70C72 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 3c76f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 000001BBD0F70C72 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 000001BBD1420472 (Hook handler)
 - 000001BBD1420472 (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - 000001BBD143507B (Hook handler)
 - 000001BBD143507B (Hook handler)
 - 000001BBD143507B (Hook handler)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 76186
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + d686b
 - C:\WINDOWS\System32\USER32.dll + 15581
 - C:\WINDOWS\System32\USER32.dll + 1505c (CallWindowProcW + 364)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + bcf3
 - C:\WINDOWS\System32\USER32.dll + 15581
 - C:\WINDOWS\System32\USER32.dll + 130cd
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - D:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 2453da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 2dbe7 (BaseThreadInitThunk + 23)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + da94c (RtlUserThreadStart + 44)

== Register States ==
RAX: 0000000000000130
RBX: 0000000000000000
RCX: 0000000000000130
RDX: 00007ff96a74e9b0
RBP: 0000000000000000
RSP: 00000082998ffb40
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff9e721a94c
R8:  00000082998fd2e0
R9:  0000000000000000
R10: 00000082998fdca8
R11: 00000082998fd300
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.4.0] alphalaneous.happy_textures
x | [v1.1.2] bitz.customprofiles
x | [v1.0.7] cdc.level_thumbnails
x | [v1.0.3] cgytrus.level-shaders-fix
  | [v2.0.0] crewly.comboburst
x | [v4.2.8] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
x | [v1.5.1] dankmeme.globed2
x | [v1.2.4] dogotrigger.deathreplay
x | [v1.3.3-alpha.2] elnexreal.copy_song_id
x | [v1.4.0] elnexreal.menuloop_randomizer
x | [v0.3.1] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.3.9] gdutilsdevs.gdutils
x | [v1.7.1] geode.custom-keybinds
x | [v3.4.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.1.0] hjfod.backups
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.2.1] itzkiba.better_progression
x | [v1.0.7] jouca.badgesapi
x | [v1.0.0] m336.autoleaderboard
x | [v1.3.7-beta.3] m336.levelinfo
x | [v1.2.1] raydeeux.endscreentweaks
x | [v1.1.21] syzzi.click_between_frames
x | [v2.12.2] techstudent10.discord_rich_presence
x | [v2.0.1] thesillydoggo.animatedprofiles
x | [v1.0.1] thesillydoggo.comment_emojis
x | [v1.6.0] thesillydoggo.qolmod

**Comment by RayDeeUx** [comment] 2024-08-24 03:29
*should* be fixed in v1.4.1 (it will just treat the filename differently). to be safe, i am using relwithdebinfo because i have not been able to use NONGs myself and would rather try reproducing the issue from windows

**Closed by RayDeeUx** 2024-08-24 03:29 UTC
