### ISSUE TITLE
[WINDOWS] Crashing on launch

### ISSUE THREAD

**Issue by Crooozy** [elnexreal/menuloop_randomizer#3] opened 2024-06-24 16:26 UTC
Log:
[2024-06-24_17-23-40.txt](https://github.com/user-attachments/files/15958581/2024-06-24_17-23-40.txt)

Installed the mod (alpha 5), and reloaded. My game kept crashing until I launched with safe mode and disabled it. I am no longer crashing.

**Comment by TheNormalestPeep** [comment] 2024-06-25 00:35
duplicate of #1

**Comment by elnexreal** [comment] 2024-07-08 00:01
fixed on 1.1.0!

**Closed by elnexreal** 2024-07-08 00:01 UTC
