### ISSUE TITLE
(Android64) Crash on startup on v1.3.0

### ISSUE THREAD

**Issue by Hanifinio** [elnexreal/menuloop_randomizer#9] opened 2024-08-09 14:20 UTC
I just updated the mod and it worked great before but now it **crashes the game on the loading screen.**

*A video showing*

https://github.com/user-attachments/assets/b874c07e-2a5e-4dc2-8b27-0784f7649739

I couldn't find anything in the *crashlog folder* but this is what was in the *logs folder*
[Geode 2024-08-09 15.14.22.log](https://github.com/user-attachments/files/16562345/Geode.2024-08-09.15.14.22.log)

**Comment by MrKareem1980** [comment] 2024-08-14 00:47
@Hanifinio Same But I Found Crashlog

**Comment by Hanifinio** [comment] 2024-08-14 05:46
You lost the crashlog? (I can see that the comment was edited)

**Comment by MrKareem1980** [comment] 2024-08-14 06:04
> You lost the crashlog? (I can see that the comment was edited)

Yes😭

**Comment by RayDeeUx** [comment] 2024-08-16 17:14
duplicate of #11 word for word

**Closed by RayDeeUx** 2024-08-16 17:14 UTC

**Comment by Hanifinio** [comment] 2024-08-18 15:32
> duplicate of #11 word for word

You do realise my one was first and the username in the video matches mine. Thanks for the fix tho but make sure you look at what issue number you're replying to and the "duplicate" (they even took my video)
